### ISSUE TITLE
Cannot make dist for pagerduty 

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-pagerduty#3]
I cannot seem to make the dist file for pagerduty to deploy over AWS on the most recent build. See screenshot below for error prompt

I run the command `make dist app_id=pagerduty`

<img width="1438" alt="Screen Shot 2023-01-02 at 6 41 06 PM" src="https://user-images.githubusercontent.com/8286670/210285207-d11e7a61-e7ef-442c-b411-b4ac781964dd.png">

Branch: Master
Last Commit: December 16th

**Comment by hanzei** [comment]
@Flinch I think this is fixed. Can you confirm?

**Comment by Flinch** [comment]
Resolved.
